title: Brian McHugh # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Having fun learning some new skills. 
  A mix of projects that I've completed 
  on my journey to learn programming and data science. 
  <br>
  <br><br>
  <a href="https://www.linkedin.com/in/brian-mchugh-a450aa104/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
