title: Brian McHugh # your name (or website title) here
logo: "/images/Untitled-Artwork (4).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Description 
  <br>
  I have created this site to highlight the skills that I have developed in data science and 
  machine learning using Python.
  <br>
  <br><br>
  <a href="https://www.linkedin.com/in/brian-mchugh-a450aa104/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
